-- AlterTable
ALTER TABLE "winover"."Funcionario" ADD COLUMN     "apovador_escalas_excepcionais" BOOLEAN,
ADD COLUMN     "aprovador_HE" BOOLEAN,
ADD COLUMN     "ativa_desktop" BOOLEAN,
ADD COLUMN     "data_admissao" TIMESTAMP(3),
ADD COLUMN     "data_atualiz_senha" TIMESTAMP(3),
ADD COLUMN     "desc_horario" TEXT,
ADD COLUMN     "empresa" TEXT,
ADD COLUMN     "foto" TEXT,
ADD COLUMN     "hora_entrada" TEXT,
ADD COLUMN     "hora_saida" TEXT,
ADD COLUMN     "id_cargo" INTEGER,
ADD COLUMN     "id_centro_custo" INTEGER,
ADD COLUMN     "id_operacao_santander" INTEGER,
ADD COLUMN     "id_tipo_discador" INTEGER,
ADD COLUMN     "intervalo_fim" TEXT,
ADD COLUMN     "intervalo_inicio" TEXT,
ADD COLUMN     "login_santander" TEXT,
ADD COLUMN     "p1_fim" TEXT,
ADD COLUMN     "p1_inicio" TEXT,
ADD COLUMN     "p2_fim" TEXT,
ADD COLUMN     "p2_inicio" TEXT,
ADD COLUMN     "p3_fim" TEXT,
ADD COLUMN     "p3_inicio" TEXT,
ADD COLUMN     "quartil" TEXT,
ADD COLUMN     "segmento_santander" TEXT,
ADD COLUMN     "senha" TEXT,
ADD COLUMN     "senha_aspect" TEXT,
ADD COLUMN     "tipo_intervalo" INTEGER,
ADD COLUMN     "ult_atualizacao" TIMESTAMP(3),
ALTER COLUMN "cpf" SET DATA TYPE VARCHAR,
ALTER COLUMN "pis" SET DATA TYPE VARCHAR,
ALTER COLUMN "hash" SET DATA TYPE VARCHAR;
