export interface Funcionario {
    id: string;
    matricula: number;
    nome: string;
    login: string;
    ativo: number;
    matricula_supervisor: number;
    dia_nao_trabalhado: boolean;
    id_campanha: number;
    ramal: number;
    data_admissao: Date | null;
    senha_aspect: string | null;
    id_cargo: number | null;
    foto: string | null;
    primeiro_acesso: string;
    data_nascimento: Date | null;
    ativa_desktop: boolean;
    tipo_intervalo: number;
    jornada_semanal: number;
    tipo_escala: number;
    aprovador_HE: boolean;
    aprovador_escalas_excepcionais: boolean;
    id_centro_custo: number;
    telefone: string;
    quartil: string;
    data_atualiz_tel: Date | null;
    data_atualiz_senha: Date | null;
    desc_horario: string | null;
    p1_inicio: string;
    p2_inicio: string;
    p3_inicio: string;
    p1_fim: string;
    p2_fim: string;
    p3_fim: string;
    intervalo_inicio: string;
    intervalo_fim: string;
    hora_entrada: string;
    hora_saida: string;
    senha: string;
    empresa: string;
    ult_atualizacao: string;
    login_santander: string;
    id_operacao_santander: number;
    segmento_santander: string;
    escala_inicia_em_semana_par: boolean;
    versao: string;
    cpf?: string;
    pis?: string;
    hash?: string;
}
